apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-trading-backend
  namespace: ai-trading
  labels:
    app: ai-trading-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-trading-backend
  template:
    metadata:
      labels:
        app: ai-trading-backend
    spec:
      containers:
      - name: ai-trading-backend
        image: gcr.io/YOUR_PROJECT_ID/ai-trading-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "postgresql://trading_user:$(cat ~/db-password.txt)@/ai_trading_db?host=/cloudsql/YOUR_PROJECT_ID:us-central1:ai-trading-postgres" # This will be replaced by sed
        
        # Redis Configuration
        - name: REDIS_URL
          value: "redis://:$(REDIS_PASSWORD)@$(REDIS_HOST):$(REDIS_PORT)/0"
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: ai-trading-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: ai-trading-config
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ai-trading-secrets
              key: REDIS_PASSWORD
        
        # Application Configuration
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: ai-trading-config
              key: FLASK_ENV
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ai-trading-secrets
              key: SECRET_KEY
        - name: ADMIN_USERNAME
          valueFrom:
            configMapKeyRef:
              name: ai-trading-config
              key: ADMIN_USERNAME
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ai-trading-secrets
              key: ADMIN_PASSWORD
        
        # Zerodha API Configuration
        - name: ZERODHA_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-trading-secrets
              key: ZERODHA_API_KEY
        - name: ZERODHA_API_SECRET
          valueFrom:
            secretKeyRef:
              name: ai-trading-secrets
              key: ZERODHA_API_SECRET
        - name: ZERODHA_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: ai-trading-secrets
              key: ZERODHA_ACCESS_TOKEN
        
        # OpenAI Configuration
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-trading-secrets
              key: OPENAI_API_KEY
        - name: OPENAI_API_BASE
          valueFrom:
            secretKeyRef:
              name: ai-trading-secrets
              key: OPENAI_API_BASE
        
        # Risk Management
        - name: MAX_DAILY_LOSS
          valueFrom:
            configMapKeyRef:
              name: ai-trading-config
              key: MAX_DAILY_LOSS
        - name: MAX_POSITION_SIZE
          valueFrom:
            configMapKeyRef:
              name: ai-trading-config
              key: MAX_POSITION_SIZE
        
        # Logging
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: ai-trading-config
              key: LOG_LEVEL
        
        volumeMounts:
        - name: logs-volume
          mountPath: /app/logs
        - name: models-volume
          mountPath: /app/models
        
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
      
      volumes:
      - name: logs-volume
        persistentVolumeClaim:
          claimName: backend-logs-pvc
      - name: models-volume
        persistentVolumeClaim:
          claimName: backend-models-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: ai-trading-backend-service
  namespace: ai-trading
spec:
  selector:
    app: ai-trading-backend
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-logs-pvc
  namespace: ai-trading
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-models-pvc
  namespace: ai-trading
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

